<?php

namespace Aether\Console\Commands;

use Aether\Aether;
use Aether\Console\Command;

class ConfigGenerateCommand extends Command
{
    protected $signature = 'config:generate';

    protected $description = 'Generate compiled configuration files.';

    public function handle()
    {
        $this->call('config:clear');

        $this->writeCompiledConfig($this->aether);
        $this->writeAetherConfig($this->aether);

        $this->info('Compiled configuration files have been generated.');

        $this->info("Environment: {$this->aether['config']['app.env']}");
    }

    protected function writeCompiledConfig($aether)
    {
        $aether['config']->saveToFile(
            "{$aether['projectRoot']}config/compiled.php"
        );
    }

    protected function writeAetherConfig($aether)
    {
        $aether['aetherConfig']->saveToFile(
            "{$aether['projectRoot']}config/autogenerated.config.xml"
        );
    }
}
